

/**
 * generated by @see ../test#casual.user (4 runs)
 */
export default {
    onlyNotifications: { email: 'Kassulke.Glen@yahoo.com',
      twoFactor: false,
      notificationStatus: true,
      id: 'dolor' },

      only2fa: { email: 'Bailey.Elnora@Lehner.us',
      twoFactor: true,
      notificationStatus: false,
      id: 'optio' },

      bothFalse: { email: 'Fadel.Ephraim@gmail.com',
      twoFactor: false,
      notificationStatus: false,
      id: 'dolorem' },

      bothTrue: { email: 'Lockman_Quincy@gmail.com',
      twoFactor: true,
      notificationStatus: true,
      id: 'totam' }
};