
/**
 * Generated by @see customCasual.previewIssueData
 */
export default {
    max: 91,
    num: 29,
    name: 'Aperiam nulla',
    articles: [{
        url: `Fugiat%20vel--44`,
        issue: 39,
        images:
            [{ url: `http://www.Dora.info/` },
            { url: `http://Hermann.org/` },
            { url: `http://Cassandra.biz/` },
            ],
        displayOrder: 97,
        views: 69,
        lede: `Aut assumenda ex nobis sequi distinctio aliquam et. Dolore beatae nemo neque ea.
     At in voluptatum quam doloribus. Dolore sed ea quo aut labore officia.`
    }
        ,
    {
        url: `Suscipit%20accusantium--43`,
        issue: 40,
        images:
            [{ url: `http://www.Tiffany.biz/` },
            { url: `http://www.Stamm.biz/` },
            { url: `http://Gladys.org/` },
            ],
        displayOrder: 45,
        views: 32,
        lede: `Soluta molestiae et ducimus molestiae doloribus similique aut aut quasi.
    Error ea soluta quam sed qui dolorum modi. Consectetur deleniti eos accusantium magni.
    Dolore amet consequatur nihil hic eos nobis sequi et vel.`
    }
        ,
    {
        url: `Error%20earum--42`,
        issue: 86,
        images:
            [{ url: `http://www.Ernestine.com/` },
            ],
        displayOrder: 77,
        views: 0,
        lede: `Ad distinctio eum voluptatem dolore eius enim exercitationem quos.
    Quaerat deleniti vitae autem quo omnis. Odit nisi quod consequatur dicta ut.
    Esse aut et et voluptatum id saepe. Quo ex rerum error. Temporibus non explicabo non iure nemo.`
    }
        ,
    {
        url: `Ut%20quis%20rerum--41`,
        issue: 80,
        images: [],
        displayOrder: 74,
        views: 96,
        lede: `Ratione debitis dolor necessitatibus voluptatum nostrum incidunt inventore ullam numquam.
    Aut fugit modi error itaque tenetur doloribus nihil. Cum dolorum quis ut.
    Autem quae vel maxime neque aut repudiandae. Eaque praesentium quia recusandae excepturi.`
    }
        ,
    {
        url: `Minus%20quod%20odio--40`,
        issue: 7,
        images:
            [{ url: `http://www.Eloisa.io/` },
            { url: `http://Gleason.org/` },
            { url: `http://Kris.info/` },
            { url: `http://Mueller.biz/` },
            { url: `http://Schmitt.ca/` },
            ],
        displayOrder: 18,
        views: 37,
        lede: `Rerum ut minus qui modi. Odit quam sint.
    Asperiores exercitationem rerum praesentium qui corrupti. Aut ut magnam est est est sed eum. Qui beatae odio et.`
    }
        ,
    {
        url: `Neque%20et%20nam--39`,
        issue: 69,
        images:
            [{ url: `http://www.Padberg.name/` },
            ],
        displayOrder: 25,
        views: 85,
        lede: `Nesciunt consequatur molestiae perferendis expedita qui minus.
    Sit dolore aut consequatur maxime. Dolores dolore ut repudiandae qui ut error.`
    }
        ,
    ]
};